apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer-service
spec:
  selector:
    app: addDeployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

 
